# pytest.ini
[pytest]
asyncio_mode = auto
# Directories or files to search for tests
testpaths = tests

# Patterns for test file discovery
python_files = test_*.py *_test.py

# Patterns for test class discovery
python_classes = Test* *Tests

# Patterns for test function discovery
python_functions = test_* check_*

